name: ci-golang-beto

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main, dev ]

jobs:

  strategy:
    matrix:
      go: [ 1.16, 1.17 ]

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v math.go

    - name: Test
      run: go test
